trunk/EZRide/EZRide/graphs/urls.py
from django.conf.urls.defaults import *
from django.views.generic import DetailView, ListView, CreateView
from views import persist_graph, pygraphviz_graph, render_graph, subgraph_index, subgraph_create, subgraph_detail, subgraph_edit
from models import Graph, SubGraph
from EZRide.user_profiles.models import UserProfile
from EZRide.graphs.models import SubGraph
from forms import SubGraphCreateForm

urlpatterns = patterns('',
                       (r'^$',
                        ListView.as_view(
                                         queryset=Graph.objects.all(),
                                         context_object_name='graphs',
                                         template_name='graphs/index.html')),
                       url(r'^(?P<graph_id>\d+)/render/(?P<subgraph_id>\d+)/$', render_graph),
                       url(r'^(?P<pk>\d+)/$', subgraph_index),                            
                       (r'^(?P<pk>\d+)/create/$', subgraph_create),
                       (r'^(?P<graph_id>\d+)/edit/(?P<subgraph_id>\d+)/$', subgraph_edit),
                       (r'^(?P<graph_id>\d+)/detail/(?P<subgraph_id>\d+)/$', subgraph_detail)                                                                    
                       )

trunk/EZRide/EZRide/urls.py
# Developed by Intento Web
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from registration.views import register #@UnresolvedImport
from profiles.views import edit_profile #@UnresolvedImport
from user_profiles.views import profile_index
from user_profiles.forms import UserProfileRegistrationForm, UserProfileEditForm

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'EZRide.views.home', name='home'),
    # url(r'^profiles/', include('user_profiles.urls')),    
    url(r'^accounts/register/$', register, {'form_class' : UserProfileRegistrationForm}, name='registration_register'),
    url(r'^accounts/', include('registration.urls')),   
    url(r'^profiles/edit/$', edit_profile, {'form_class': UserProfileEditForm,}, name='profiles_edit_profile'),
    url(r'^profiles/$', profile_index),
    url(r'^profiles/', include('profiles.urls')),   
    (r'^graphs/', include('graphs.urls')),              
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),      

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
   # url(r'^admin/graphs/graph', include('graphs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    
)

trunk/EZRide/EZRide/graphs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage

fs = FileSystemStorage(location='/home/gabriel/DEV/Python/Eclipse_workspace/EZRide/EZRide/web-content/media/')
fu = 'uploads'

class Graph(models.Model):
    name = models.CharField(max_length=200)        
    dot_file = models.FileField(upload_to=fu, storage=fs)
    def __unicode__(self):
        return self.name
    
class Node(models.Model):
    name = models.CharField(max_length=200)    
    label = models.CharField(max_length=200)    
    graph = models.ForeignKey(Graph)    
    def __unicode__(self):
        return self.label
    
class Edge(models.Model):
    name = models.CharField(max_length=200)   
    graph = models.ForeignKey(Graph)
    def __unicode__(self):
        return self.name
    
class SubGraph(models.Model):    
    name = models.CharField(max_length=200, unique=True)
    user = models.ForeignKey(User)
    graph = models.ForeignKey(Graph)
    nodes = models.ManyToManyField(Node, blank=True)
    edges = models.ManyToManyField(Edge, blank=True)
    def __unicode__(self):
        return self.name

trunk/EZRide/EZRide/graphs/forms.py
from django import forms
from django.forms import ModelForm, Form
from django.forms.models import modelformset_factory
from django.forms.models import BaseModelFormSet
from models import SubGraph, Graph, Node, Edge


attrs_dict = { 'class': 'required' }

class SubGraphCreateForm(forms.ModelForm):  
    def __init__(self, graph_id, *args, **kwargs):
        super(SubGraphCreateForm, self).__init__(*args, **kwargs)
        self.fields['nodes'] = forms.ModelMultipleChoiceField(queryset=Node.objects.filter(graph__id=graph_id).order_by('id'), widget=forms.CheckboxSelectMultiple)
    class Meta:
        model = SubGraph
        fields = ('name', 'nodes')
        
class SubGraphDetailForm(forms.ModelForm):
    class Meta:
        model = SubGraph
        fields = ('name', 'nodes')

trunk/EZRide/EZRide/graphs/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Simple example for rendering a graph with the Django web framework.
See
http://www.djangoproject.com/
and
http://www.djangobook.com/en/beta/chapter11/

"""
#    Copyright (C) 2007 by 
#    Aric Hagberg <hagberg@lanl.gov>
#    Dan Schult <dschult@colgate.edu>
#    Manos Renieris, http://www.cs.brown.edu/~er/
#    Distributed with BSD license.     
#    All rights reserved, see LICENSE for details.
from django.shortcuts import render_to_response, HttpResponseRedirect
from django.contrib import admin

from django.core.context_processors import csrf
from models import Graph, Node, Edge, SubGraph
from forms import SubGraphCreateForm, SubGraphDetailForm
from django.forms.models import modelformset_factory
from django.template.context import RequestContext

try:
    from django.http import HttpResponse
except ImportError: # this won't run without Django, print message 
    print "Django not found."
    
def persist_graph(request, graph_id):
    import pygraphviz as P
    import networkx as N
    
    graph = Graph.objects.get(pk=graph_id)
    dot_path = graph.dot_file.storage.location + '/' + graph.dot_file.name
    G = P.AGraph() # init empty graph
    try:
         
        G.read(dot_path) #read file      
        nodes = G.nodes()
        edges = G.edges() 
        Node.objects.filter(graph__id=graph_id).delete()
        Edge.objects.filter(graph__id=graph_id).delete()               
        for node in nodes:            
            new_node = Node()
            new_node.graph = graph
            new_node.name = node
            new_node.label = node.attr['label']
            new_node.save()
        for edge in edges:
            new_edge = Edge()
            new_edge.graph = graph
            new_edge.name = edge
            new_edge.save()
    except:
        return False
    return HttpResponse(pygraphviz_graph(request, G)) #response

def pygraphviz_graph(request, graph):
    import pygraphviz as P
    import networkx as N
  
    G = graph
    G.layout(prog='dot') #dot language
    img = G.draw(format='svg') # draw png    
    return HttpResponse(img, mimetype='image/svg+xml') #response



def shortest_path_rec(G, lista, i):
    import networkx as N
    L = N.Graph()
    J = N.Graph()  
      
    try:
        edgelist = N.shortest_path(G, source=lista[i],target=lista[(i+1)])
        L = G.subgraph(edgelist)
        J.add_edges_from(L.edges())
        edgelist = shortest_path_rec(G, lista, (i+1))
        L.add_edges_from(edgelist)
        J.add_edges_from(L.edges())
        J.node[lista[i]]= G.node[lista[i]]
        J.graph['color']='red'
        return J.edges()
    except (IndexError, RuntimeError):
        J.node[lista[i]]= G.node[lista[i]]
        J.graph['color']='red'
        return J.edges() 

def render_graph(request, graph_id, subgraph_id):
    import pygraphviz as P
    import networkx as N
    
    graph = Graph.objects.get(pk=graph_id)   
    dot_path = graph.dot_file.storage.location + '/' + graph.dot_file.name          
    G = P.AGraph() # init empty graph   
    try:
        G.read(dot_path) #read file                
        NG = N.Graph(G) #pyGraphViz to networkX; full graph
    except:
        pass
    if subgraph_id <> '0': #render subgraph svg      
        SG = N.Graph() #subgraph networkX 
        nodes = Node.objects.filter(subgraph__id=subgraph_id) #nodes in db
        for node in nodes:
            new_node = NG.node['name']=node.name
            SG.add_node(new_node)                      
        nodes = SG.nodes()
        edges = shortest_path_rec(NG, nodes,0)
        SG.add_edges_from(edges)        
        NSG = N.Graph()
        nodes = Node.objects.filter(graph__id=graph_id)
        for node in nodes:
            if SG.has_node(node.name):
                NSG.add_node(node.name, label=node.label, color='red')            
        NSG.add_edges_from(edges, color='red')
        
        
        NG = N.Graph(G)
        FG = N.compose(NSG, NG)
        FG.name = 'test'
        FG = N.to_agraph(FG)        
        #NEW_GRAPH = funcao de colorir(AGraph(), AGraph.edges()):retorna AGraph()        
        #SG = N.to_agraph(NSG)             
        #NG.graph.update(NSG.graph)
        #NG.name = 'test'
        #FG = N.to_agraph(NG)          
     
        FG.layout(prog='dot') #dot language
        graphView = FG.draw(format='svg') # draw svg
    else:
        G.layout(prog='dot') #dot language
        graphView = G.draw(format='svg') # draw svg       
    return HttpResponse(graphView, mimetype='image/svg+xml') #response

def subgraph_index(request, pk):
    subgraphs = SubGraph.objects.filter(graph__id=pk).exclude(user__id=request.user.id)
    graph_id = pk
    return render_to_response('graphs/subgraph_index.html', {'user': request.user, 'subgraphs': subgraphs, 'graph_id': graph_id }, mimetype='text/html')

def subgraph_create(request, pk):
    if request.method == 'POST': # If the form has been submitted...
        form = SubGraphCreateForm(pk, request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            # Process the data in form.cleaned_data
            # ...                        
            subgraph = form.save(commit=False)
            subgraph.name = form.cleaned_data['name']            
            subgraph.graph = Graph.objects.get(pk=pk)
            subgraph.user = request.user
            subgraph.save()
            subgraph.nodes = form.cleaned_data['nodes']   
            subgraph.save()
            subgraph_id = subgraph.id    
            graph_id = subgraph.graph.id      
            return subgraph_detail(request, graph_id, subgraph_id)
        else:      
            return HttpResponseRedirect('/profiles/') # Redirect after POST
    else:
        form = SubGraphCreateForm(pk)   # An unbound form      
    return render_to_response('graphs/subgraph_create.html', {                                                     
        'user': request.user,
        'form': form,
        'graph_id': pk       
    }, context_instance=RequestContext(request))
    
def subgraph_edit(request, graph_id, subgraph_id):
    if request.method == 'POST': # If the form has been submitted...
        form = SubGraphDetailForm(request.POST, instance=SubGraph.objects.get(pk=subgraph_id)) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            # Process the data in form.cleaned_data
            # ...                        
            subgraph = form.save(commit=False)
            subgraph.name = form.cleaned_data['name']            
            subgraph.graph = Graph.objects.get(pk=graph_id)
            subgraph.user = request.user
            subgraph.save()
            subgraph.nodes = form.cleaned_data['nodes']   
            subgraph.save()            
            return subgraph_detail(request, graph_id, subgraph_id)
        else:      
            return HttpResponseRedirect('/profiles/') # Redirect after POST
    else:
        form = SubGraphDetailForm(instance=SubGraph.objects.get(pk=subgraph_id))   # An unbound form      
    return render_to_response('graphs/subgraph_edit.html', {                                                     
        'user': request.user,
        'form': form,
        'graph_id': graph_id,
        'subgraph_id': subgraph_id       
    }, context_instance=RequestContext(request))
    
def subgraph_detail(request, graph_id, subgraph_id):
    subgraph = SubGraph.objects.get(pk=subgraph_id)        
    nodes = Node.objects.filter(subgraph__id=subgraph_id)  
    return render_to_response('graphs/subgraph_detail.html', {                                                     
        'user': request.user,
        'subgraph': subgraph,        
        'nodes': nodes       
    }, context_instance=RequestContext(request))
    

trunk/EZRide/EZRide/web-content/templates/graphs/index.html
{% extends "site/base.html" %}

{% block title %}Cidades{% endblock %} 

{% block content %}
	{% if graphs %}
		<h1>Selecione uma cidade:</h1>
    	<ul>
    	{% for graph in graphs %}
        	<li><a href="/graphs/{{ graph.id }}/">{{ graph.name }}</a></li>
    	{% endfor %}
    	</ul>    	
	{% else %}
    	<p>Nenhuma cidade cadastrada.</p>    	
	{% endif %}
{% endblock %}

{% block content-related %}
{% endblock %}

trunk/EZRide/EZRide/web-content/templates/graphs/subgraph_create.html
{% extends "site/base.html" %}

<h1>Criar rota</h1>

{% if error_message %}
<p>
	<strong>{{ error_message }}</strong>
</p>
{% endif %} {% block content %} {% if user.is_active %}
<div id="graph"></div>
<script>
	var svg;
	head.ready(function() {
		loadSVG($('#graph_id').val(), 0);
		svg = $('#graph').svg('get');		
	});	
</script>
<form method="POST" action="">
	{% csrf_token %}
	<p>
		<label for="id_name">Nome Rota:</label> {% if form.name.errors %}
	<p class="errors">{{ form.name.errors.as_text }}</p>
	{% endif %} {{ form.name }}
	</p>
	<p>
		<label for="id_nodes">Bairros:</label> {% if form.nodes.errors %}
	<p class="errors">{{ form.nodes.errors.as_text }}</p>
	{% endif %} {{ form.nodes }}
	</p>
	{% if form.errors %}
	<p class="errors">{{ form.errors.as_text }}</p>
	{% endif %} <input type="submit" name="submit" value="Criar Rota"
		id="submit">
</form>

{% else %}
<p>É necessário estar cadastrado e com a conta ativada para poder
	criar rotas.</p>
{% endif %} {% endblock %} {% block content-related %}
<input type="text" id="graph_id" hidden="true" value="{{ graph_id }}">
{% endblock %}

trunk/EZRide/EZRide/web-content/templates/graphs/subgraph_detail.html
{% extends "site/base.html" %}

<h1>Detalhes Rota</h1>

{% if error_message %}
<p>
	<strong>{{ error_message }}</strong>
</p>
{% endif %} {% block content %}

<div id="graph"></div>
<script>
	var svg;
	head.ready(function() {
		svg = loadSVG($('#graph_id').val(), $('#subgraph_id').val());
		graphHover(svg);
	});

	function set_user(user_id) {
		$('#id_user').val(user_id);
		$('#id_user').hide();
	}
</script>

<p>
	<strong>Nome:</strong><br>{{ subgraph.name }}
</p>
<p>
	<strong>Bairros:</strong><br>
</p>
<ul>
	{% for node in nodes %}
	<li>
		<p>{{ node.label }}</p>
	</li> 
	{% endfor %}
</ul>
{% endblock %} 
{% block content-related %} 
<input type="text" id="user_id" hidden="true" value="{{ user.id }}">
<input type="text" id="graph_id" hidden="true" value="{{ subgraph.graph.id }}">
<input type="text" id="subgraph_id" hidden="true" value="{{ subgraph.id }}">
{% endblock %}

trunk/EZRide/EZRide/web-content/templates/graphs/subgraph_edit.html
{% extends "site/base.html" %}

<h1>Editar Rota</h1>

{% if error_message %}
<p>
	<strong>{{ error_message }}</strong>
</p>
{% endif %} 
{% block content %} 
{% if user.is_active %}
<div id="graph"></div>
<script>
	var svg;
	head.ready(function() {
		svg = loadSVG($('#graph_id').val(), $('#subgraph_id').val());
		graphHover(svg);	
	});
	
	function set_user(user_id) {
		$('#id_user').val(user_id);
		$('#id_user').hide();	
	}

	
</script>
<form method="POST" action="">
	{% csrf_token %}	
	{{ form.as_p }}        
	<input type="submit" name="submit" value="Atualizar Rota" id="submit">
</form>
{% else %}
<p>É necessário estar cadastrado e com a conta ativada para poder editar rotas.</p>
{% endif %} 
{% endblock %} 
{% block content-related %} 
<input type="text" id="user_id" hidden="true" value="{{ user.id }}">
<input type="text" id="graph_id" hidden="true" value="{{ graph_id }}">
<input type="text" id="subgraph_id" hidden="true" value="{{ subgraph_id }}">
{% endblock %}

trunk/EZRide/EZRide/web-content/templates/graphs/subgraph_index.html
{% extends "site/base.html" %}

{% block title %}Rotas{% endblock %} 

{% if user.is_active %}
{% block content %}
	{% if subgraphs %}
		<h1>Selecione uma rota para visualizar, ou crie uma nova:</h1>
    	<ul>
    	{% for subgraph in subgraphs %}
        	<li><a href="/graphs/{{ subgraph.graph_id }}/detail/{{ subgraph.id }}/">{{ subgraph.name }}</a></li>        	
    	{% endfor %}    	
    	</ul>    	    	
	{% else %}
    	<p>Nenhuma rota cadastrada.</p>
	{% endif %}
{% endblock %}
{% endif %}

{% block content-related %}
<p><a href="/graphs/{{ graph_id }}/create/">Criar Rota</a></p>
{% endblock %}